---
- name: install required packages
  package:
    name: '{{ item }}'
    state: present
  become: true
  with_items: '{{ PACKAGES }}'

- name: install the_silver_searcher
  become: true
  copy:
    src: ag
    dest: /usr/bin/ag
    mode: '0755'

- name: install firebase
  get_url:
    url: 'https://firebase.tools/bin/linux/latest'
    dest: /usr/bin/firebase
    mode: '0755'

- name: install epel-release
  become: true
  shell: 'amazon-linux-extras install -y epel'

- name: install nodejs after epel
  become: true
  package:
    name: nodejs
    state: present

- name: download aptly package
  get_url:
    url: 'https://github.com/aptly-dev/aptly/releases/download/v{{ aptly_version }}/aptly_{{ aptly_version }}_linux_amd64.tar.gz'
    dest: "{{ USER.home }}"

- name: untar aptly package
  unarchive:
    copy: no
    src: "{{ USER.home }}/aptly_{{ aptly_version }}_linux_amd64.tar.gz"
    dest: "{{ USER.home }}"

- name: install aptly
  become: true
  command: install -m 0755 {{ USER.home }}/aptly_{{ aptly_version }}_linux_amd64/aptly /usr/local/bin

# vim: set expandtab:ts=2
