---
- hosts: '{{ inventory }}'
  gather_facts: yes

  tasks:
  - name: fetch log
    ignore_errors: yes
    fetch:
      src: "/home/{{ ansible_user }}/latest/zerolog-harmony.log"
      dest: "/tmp/logs/{{ host }}.log"
      flat: yes
      validate_checksum: no
