---
- hosts: '{{ inventory }}'
  serial: "{{ stride | default(5) }}"
  gather_facts: no
  become: true
  vars:
    check_consensus: "{{ check | default('false') }}"

  tasks:
  - name: "stop harmony service"
    systemd:
      name: harmony
      state: stopped

  - name: "install harmony binary"
    get_url: 
      url: "https://s3-us-west-1.amazonaws.com/pub.harmony.one/release/linux-x86_64/{{ bucket }}/static/harmony"
      dest: /usr/sbin/harmony
      mode: '0755'
      force: yes

  - name: "archive harmony log"
    command: mv /home/ubuntu/latest/zerolog-harmony.log /home/ubuntu/latest/zerolog-harmony.log.bak

  - name: "restart harmony service"
    systemd:
      name: harmony
      state: started

  - name: "wait 1 minutes for consensus"
    pause:
      minutes: 1

  - name: "check on the first BINGO/HOORAY every 30 sec for 10 minutes on validator"
    shell:
    args:
      cmd: "tail -n 30 zerolog-harmony.log | grep -m 1 -E 'HOORAY|BINGO' | jq -r .time"
      chdir: "/home/ubuntu/latest"
    register: firstConsensus
    until: firstConsensus.stdout.find("T") != -1
    retries: 20
    delay: 20
    when: check_consensus == 'true'

