---
- hosts: '{{ inventory }}'
  gather_facts: no
  become: true

  tasks:
  - name: "stop harmony service"
    systemd:
      name: harmony
      state: stopped

  - name: "install harmony binary"
    get_url: 
      url: "https://s3-us-west-1.amazonaws.com/pub.harmony.one/release/linux-x86_64/{{ bucket }}/static/harmony"
      dest: /usr/sbin/harmony
      mode: '0755'
      force: yes

  - name: "archive harmony log"
    command: mv /home/ubuntu/latest/zerolog-harmony.log /home/ubuntu/latest/zerolog-harmony.log.bak

  - name: "restart harmony service"
    systemd:
      name: harmony
      state: started
